kind: PersistentVolume
apiVersion: v1
metadata:
  name: envoy-local-jwks-volume
  labels:
    type: local
    app: {{ .Release.Name }}-envoy
spec:
  storageClassName: manual
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path:  {{ .Values.localJwks }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: envoy-local-jwks-claim
  labels:
    app: {{ .Release.Name }}-envoy
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Mi

